name: ChaosFrontier
version: '1.0-SNAPSHOT'
main: xyz.v4nixd.chaosFrontier.ChaosFrontier
api-version: '1.20'

depend:
  - packetevents
  - HologramLib
  - PlaceholderAPI

commands:
  genworld:
    description: World generation
    usage: /genworld [worldName]
  teams:
    description: Выбрать команду
    usage: /teams